#!/bin/bash

set -euo pipefail

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() {
    echo -e "${GREEN}[INFO]${NC} $*"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $*" >&2
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $*" >&2
}

log_section() {
    echo -e "\n${BLUE}==== $* ====${NC}\n"
}

# Root check
if [ "$EUID" -ne 0 ]; then
    log_error "This script must be run as root (use: sudo $0)"
    exit 1
fi

log_section "Overdrive-AMC Setup & Configuration"

# Step 1: Run installation
log_section "Step 1: Installing Overdrive-AMC from GitHub"
log_info "Running install.sh from GitHub..."

if ! bash <(curl -fsSL https://raw.githubusercontent.com/alittler/overdrive-amc/main/install.sh); then
    log_error "Installation failed"
    exit 1
fi

log_info "Installation successful!"

# Step 2: Detect physical disks/partitions
log_section "Step 2: Detecting Physical Disks & Mount Points"

declare -a MOUNTS
declare -a DISK_INFO

log_info "Scanning for physical storage..."

# Get all block devices and mount points
while IFS= read -r device mountpoint fstype; do
    # Skip loop devices, ram, and tmpfs
    if [[ "$device" =~ ^/dev/(loop|ram|zram|sr) ]] || [[ "$fstype" =~ ^(tmpfs|devtmpfs|sysfs|proc)$ ]]; then
        continue
    fi
    
    # Only include actual disks/partitions
    if [[ "$device" =~ ^/dev/(sd|nvme|vd) ]] && [ -n "$mountpoint" ]; then
        MOUNTS+=("$mountpoint")
        DISK_INFO+=("$device:$mountpoint")
    fi
done < <(lsblk -npo NAME,MOUNTPOINT,FSTYPE 2>/dev/null || true)

if [ ${#MOUNTS[@]} -eq 0 ]; then
    log_warn "No mounted physical disks detected"
    log_info "Available mount points:"
    lsblk -o NAME,SIZE,MOUNTPOINT | head -20
else
    log_info "Found ${#MOUNTS[@]} mounted disk(s):"
    for info in "${DISK_INFO[@]}"; do
        device="${info%%:*}"
        mount="${info##*:}"
        size=$(lsblk -dnpo SIZE "$device" 2>/dev/null | head -1 || echo "Unknown")
        log_info "  └─ $device ($size) mounted at $mount"
    done
fi

# Step 3: Copy code to shared location
log_section "Step 3: Setting Up Shared Location"

INSTALL_DIR="/opt/overdrive-amc"
SHARED_LOCATION="/opt/overdrive-data"

log_info "Creating shared data directory: $SHARED_LOCATION"
mkdir -p "$SHARED_LOCATION" || {
    log_error "Failed to create $SHARED_LOCATION"
    exit 1
}

# Ensure overdrive is installed
if [ -d "$INSTALL_DIR" ]; then
    log_info "Copying overdrive code to shared location..."
    
    # Copy main script
    cp -v "$INSTALL_DIR/overdrive.sh" "$SHARED_LOCATION/" || {
        log_error "Failed to copy overdrive.sh"
        exit 1
    }
    
    # Copy install script
    cp -v "$INSTALL_DIR/install.sh" "$SHARED_LOCATION/" || {
        log_error "Failed to copy install.sh"
        exit 1
    }
    
    # Copy README
    if [ -f "$INSTALL_DIR/README.md" ]; then
        cp -v "$INSTALL_DIR/README.md" "$SHARED_LOCATION/" || {
            log_error "Failed to copy README.md"
            exit 1
        }
    fi
    
    # Make executable
    chmod +x "$SHARED_LOCATION/overdrive.sh"
    chmod +x "$SHARED_LOCATION/install.sh"
    
    log_info "Code copied successfully"
else
    log_error "Overdrive not found at $INSTALL_DIR"
    exit 1
fi

# Step 4: Create configuration file
log_section "Step 4: Creating Configuration"

CONFIG_FILE="$SHARED_LOCATION/config.sh"

cat > "$CONFIG_FILE" << 'EOF'
#!/bin/bash
# Overdrive-AMC Configuration
# Generated by setup.sh

# Installation information
INSTALL_DIR="/opt/overdrive-amc"
SHARED_DIR="/opt/overdrive-data"
SETUP_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
SETUP_BY="${SUDO_USER:-root}"

# Detected storage information (populated by setup.sh)
DETECTED_MOUNTS=()
DETECTED_DISKS=()

EOF

# Add detected mount points to config
log_info "Writing mount points to config..."
for mount in "${MOUNTS[@]}"; do
    size=$(df -h "$mount" | tail -1 | awk '{print $2}')
    used=$(df -h "$mount" | tail -1 | awk '{print $3}')
    avail=$(df -h "$mount" | tail -1 | awk '{print $4}')
    echo "# Mount: $mount (Total: $size, Used: $used, Available: $avail)" >> "$CONFIG_FILE"
    echo "DETECTED_MOUNTS+=(\"$mount\")" >> "$CONFIG_FILE"
done

chmod +x "$CONFIG_FILE"
log_info "Configuration saved to $CONFIG_FILE"

# Step 5: Display summary
log_section "Setup Complete!"

cat << EOF

${GREEN}✓ Installation successful!${NC}

Locations:
  • Installation:    $INSTALL_DIR
  • Shared code:     $SHARED_LOCATION
  • Configuration:   $CONFIG_FILE

Detected Storage:
EOF

for mount in "${MOUNTS[@]}"; do
    usage=$(df -h "$mount" | tail -1 | awk '{printf "%s / %s (%s used)", $3, $2, int($5)}')
    echo "  • $mount - $usage"
done

cat << EOF

Next Steps:
  1. Review configuration:
     cat $CONFIG_FILE

  2. Run overdrive-amc:
     $SHARED_LOCATION/overdrive.sh

  3. Check logs:
     ls -la $SHARED_LOCATION/

Need help? See:
  $SHARED_LOCATION/README.md

EOF

log_info "Setup complete!"
